def playgame():
    os.system("python3 maze.py")
def hjgame():
    tk = tkinter.Tk()
    frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
    frame.pack(fill=BOTH,expand=1)
    label = tkinter.Label(frame, text="Installing hj-game")
    label.pack(fill=X, expand=1)
    label2 = tkinter.Label(frame, text="Downloading...")
    label2.pack(fill=X, expand=1)
    os.system("curl -o ~/game.zip https://raw.githubusercontent.com/hu10xiaorui/hj-game/master/hj-game-master.zip")
    label2 = tkinter.Label(frame, text="Unziping...")
    label2.pack(fill=X, expand=1)
    os.system("unzip ~/game.zip -d ~/")
    label2 = tkinter.Label(frame, text="Deleting zip...")
    label2.pack(fill=X, expand=1)
    os.system("rm ~/game.zip")
    label2 = tkinter.Label(frame, text="Placing hj-game.command to home folder")
    label2.pack(fill=X, expand=1)
    os.system("curl -o ~/hj-game.command https://raw.githubusercontent.com/hu10xiaorui/hj-game/master/hj-game.command")
    label2 = tkinter.Label(frame, text="Giving Permisions")
    label2.pack(fill=X, expand=1)
    os.system("chmod +x hj-game.command")
    label2 = tkinter.Label(frame, text="Success! run hj-game.command to play game!")
    label2.pack(fill=X, expand=1)
    tk.mainloop()


def howto():
    tk = tkinter.Toplevel()
    frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
    frame.pack(fill=BOTH,expand=1)
    label = tkinter.Label(frame, text="How to play")
    label.pack(fill=X, expand=1)
    label2 = tkinter.Label(frame, text="Use arrows keys to move, the mission is to get all the coins")
    label2.pack(fill=X, expand=1)
def main():
    tk = tkinter.Tk()
    frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
    frame.pack(fill=BOTH,expand=1)
    label = tkinter.Label(frame, text="Hj-Zombie")
    label.pack(fill=X, expand=1)
    label2 = tkinter.Label(frame, text="A improved veersion of Zombie head maze game Python turtle")
    label2.pack(fill=X, expand=1)
    play = tkinter.Button(frame,text="Play",command=playgame)
    play.pack()
    Howto = tkinter.Button(frame,text="How to play",command=howto)
    Howto.pack()
    moregamebutton = tkinter.Button(frame,text="More Game",command=moregame)
    moregamebutton.pack()
    exit = tkinter.Button(frame,text="Exit",command=tk.destroy)
    exit.pack()
    tk.mainloop()
def moregame():
    tk = tkinter.Tk()
    frame = tkinter.Frame(tk, relief=RIDGE, borderwidth=2)
    frame.pack(fill=BOTH,expand=1)
    label = tkinter.Label(frame, text="More Game")
    label.pack(fill=X, expand=1)
    label2 = tkinter.Label(frame, text="The following options requires internet access")
    label2.pack(fill=X, expand=1)
    play = tkinter.Button(frame,text="Play hj-game",command=hjgame)
    play.pack()
    tk.mainloop()
import tkinter
import os
from tkinter.constants import *
main()
